apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.7/manifests/install.yaml
- projects/app-deploy.yaml
# - applications/ns1/podinfo-ns1.yaml
# - applications/ns2/podinfo-ns2.yaml
# - applicationsets/podinfo-matrix.yaml
# - applicationsets/podinfo-list.yaml

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: merge
  literals:
  - server.insecure=false
